title: Dark Souls III Boss List & Guide
email: kacper.mush@gmail.com
description: "Stay safe, friend. Don't you dare go hollow."
# FOR STUDENTS
# url: "https://students.mimuw.edu.pl"
# baseurl: "/~kg459029/www1"
# FOR GITHUB
url: "https://kacper-mush.github.io"
baseurl: "/AWWW1"
github_username:  kacper-mush
author: Kacper Grzybowski

# Build settings
theme: minima

sass:
  load_paths:
    - _sass
    - assets

plugins:
  - jekyll-feed

exclude:
  - .venv/
  - main.py
  - ddgs_cache/
  - requirements.txt